steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}",
        "-f",
        "Dockerfile.backend",
        ".",
      ]
      
images:
  - "${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}"

substitutions:
  _LOCATION: asia-southeast2
  _PROJECT_ID: <YOUR_GCP_PROJECT_ID>
  _REPO: <YOUR_REPOSITORY_NAME>
  _IMAGE: siapkerja-backend
